### Downloaded data scraped by robot which crawls all Kickstarter projects and collects data in JSON format from https://webrobots.io/kickstarter-datasets/

### Actual file name:  https://s3.amazonaws.com/weruns/forfun/Kickstarter/Kickstarter_2017-05-15T22_21_11_300Z.json.gz
    
### Renamed to Kickstarter_js.json

In [276]:
### Import JSON file into pandas dataframe
# import pandas as pd
# df = pd.read_json('Kickstarter_js.json', lines = True)

In [4]:
#Since it's almost 1GB file and the reader appears to be slow - saving a pickle

# import pickle
# pickle.dump(df,open("kicks.pkl",'wb'))

In [1]:
# Loading previously saved data

import pickle
df = pickle.load(open("kicks.pkl",'rb'))

In [2]:
### Take a look at the first 5 rows of the data
df.head(5)

,created_at,data,id,robot_id,run_id,table_id
0,2017-05-15 22:51:47.958368,"{'id': 320979084, 'goal': 2500, 'name': 'Eat L...",352850838,Kickstarter,Kickstarter_2017-05-15T22_21_11_300Z,Kickstarter
1,2017-05-15 22:51:47.958368,"{'id': 277020703, 'goal': 4500, 'name': 'The P...",352850838,Kickstarter,Kickstarter_2017-05-15T22_21_11_300Z,Kickstarter
2,2017-05-15 22:51:47.958368,"{'id': 1412712121, 'goal': 2500, 'name': 'En l...",352850838,Kickstarter,Kickstarter_2017-05-15T22_21_11_300Z,Kickstarter
3,2017-05-15 22:51:47.958368,"{'id': 439696234, 'goal': 10000, 'name': 'Unde...",352850838,Kickstarter,Kickstarter_2017-05-15T22_21_11_300Z,Kickstarter
4,2017-05-15 22:51:47.958368,"{'id': 820236173, 'goal': 7900, 'name': 'Adven...",352850838,Kickstarter,Kickstarter_2017-05-15T22_21_11_300Z,Kickstarter

### All the data is read in into column 'data'
### It's a dictionary of dictionaries --> should be handled by JSON reader

In [3]:
### Drop fluff
df= df['data']

In [6]:
### Parse "data" into a data frame reading it as JSON
df_parsed = pd.read_json(df.to_json(orient="records"))

In [7]:
df_parsed.head(3)

,backers_count,blurb,category,country,created_at,creator,currency,currency_symbol,currency_trailing_code,deadline,...,profile,slug,source_url,spotlight,staff_pick,state,state_changed_at,static_usd_rate,urls,usd_pledged
0,29,"“Eat Local In Barcelona"" breaks down the compl...","{'id': 48, 'name': 'Nonfiction', 'slug': 'publ...",US,2015-11-09 17:19:18,"{'id': 1140825012, 'name': 'Ashley and Alex', ...",USD,$,True,1459011263,...,"{'id': 2219284, 'name': 'Eat Local in Barcelon...",eat-local-in-barcelona-a-guide-to-catalan-cuisine,https://www.kickstarter.com/discover/categorie...,True,False,successful,2016-03-26 16:54:23,1.000000,{'web': {'project': 'https://www.kickstarter.c...,2700.000000
1,401,Publishing the 'Wife in Space' blog as a colle...,"{'id': 48, 'name': 'Nonfiction', 'slug': 'publ...",GB,2015-05-28 09:20:01,"{'id': 1428795197, 'name': 'Neil Perryman', 'u...",GBP,£,False,1445034600,...,"{'id': 1925846, 'name': None, 'blurb': None, '...",the-pompous-tory-the-wife-in-space-volume-3,https://www.kickstarter.com/discover/categorie...,True,True,successful,2015-10-16 22:30:12,1.515586,{'web': {'project': 'https://www.kickstarter.c...,14445.045591
2,76,Hjälp mig skriva historia genom att trycka den...,"{'id': 48, 'name': 'Nonfiction', 'slug': 'publ...",SE,2016-11-06 16:08:17,"{'id': 1943225696, 'name': 'Rasmus Bååth', 'ur...",SEK,kr,True,1480892340,...,"{'id': 2748478, 'name': 'En liten groggpraktik...",en-liten-groggpraktika,https://www.kickstarter.com/discover/categorie...,True,False,successful,2016-12-04 22:59:00,0.110021,{'web': {'project': 'https://www.kickstarter.c...,964.886889

In [9]:
### Check distribution by country (associtated with creator's location)
df_parsed.country.value_counts()

US    140750
GB     16644
CA      7524
AU      3996
DE      1943
NL      1539
FR      1453
IT      1374
ES      1064
SE       903
NZ       734
DK       626
MX       590
IE       423
NO       394
CH       373
BE       321
AT       264
HK       176
SG       174
LU        23
Name: country, dtype: int64

In [16]:
### To keep it clean and simple for NLP analysis, stick to one language only, English
### Given that population of English-speaking countries is dominated by the U.S. and Canada, 
### the second largest host of projects, is dual-speaking, data set will be limited to US only

df_us = df_parsed.query('country == "US"').reset_index()
df_us.shape

(140750, 33)

In [17]:
### Drop columns that are not going to be used in NLP/clustering analysis
df_us_ = df_us.drop(['currency_symbol',
'currency_trailing_code',
'disable_communication',
'friends',
'index',                     
'is_backing',
'is_starred',
'permissions',
'photo',
'slug',
'source_url',
'spotlight',
'static_usd_rate',
'urls'], axis=1)

In [18]:
df_us_.head(5)

,backers_count,blurb,category,country,created_at,creator,currency,deadline,goal,id,launched_at,location,name,pledged,profile,staff_pick,state,state_changed_at,usd_pledged
0,29,"“Eat Local In Barcelona"" breaks down the compl...","{'id': 48, 'name': 'Nonfiction', 'slug': 'publ...",US,2015-11-09 17:19:18,"{'id': 1140825012, 'name': 'Ashley and Alex', ...",USD,1459011263,2500.0,320979084,2016-02-25 17:54:23,"{'id': 753692, 'name': 'Barcelona', 'slug': 'b...",Eat Local in Barcelona - A Guide to Catalan Cu...,2700.00,"{'id': 2219284, 'name': 'Eat Local in Barcelon...",False,successful,2016-03-26 16:54:23,2700.00
1,505,Help us spark intelligent discussions about ra...,"{'id': 48, 'name': 'Nonfiction', 'slug': 'publ...",US,2015-07-31 21:22:59,"{'id': 1573482716, 'name': 'PM Press', 'slug':...",USD,1445032800,10000.0,439696234,2015-09-15 21:18:32,"{'id': 2463583, 'name': 'Oakland', 'slug': 'oa...",Understanding Jim Crow: Racist Memorabilia & S...,17321.00,"{'id': 2044569, 'name': None, 'blurb': None, '...",True,successful,2015-10-16 22:00:13,17321.00
2,172,How I accidentally made a desert phone booth w...,"{'id': 48, 'name': 'Nonfiction', 'slug': 'publ...",US,2014-08-14 23:59:45,"{'id': 1947700420, 'name': 'Doc Daniels', 'slu...",USD,1411239661,7900.0,820236173,2014-08-21 19:01:01,"{'id': 2495997, 'name': 'South Bisbee', 'slug'...",Adventures with the Mojave Phone Booth,8773.17,"{'id': 1290905, 'name': None, 'blurb': None, '...",True,successful,2014-09-20 19:01:03,8773.17
3,31,The Heart of A Caregiver book will inspire tho...,"{'id': 48, 'name': 'Nonfiction', 'slug': 'publ...",US,2016-11-12 20:56:09,"{'id': 733132432, 'name': 'Evelyn Johnson-Tayl...",USD,1481825510,2500.0,1522087420,2016-11-15 18:11:50,"{'id': 2503863, 'name': 'Tampa', 'slug': 'tamp...",The Heart of A Caregiver My journey of caring ...,2520.00,"{'id': 2756887, 'name': 'The Heart of A Caregi...",False,successful,2016-12-15 18:11:50,2520.00
4,274,The Idea Shapers book gives you the power to p...,"{'id': 48, 'name': 'Nonfiction', 'slug': 'publ...",US,2014-11-20 04:45:57,"{'id': 1642130654, 'name': 'Brandy Agerbeck', ...",USD,1425168000,5000.0,1079350420,2015-01-28 21:58:24,"{'id': 2379574, 'name': 'Chicago', 'slug': 'ch...",The Idea Shapers | Drawing as your best thinki...,12500.00,"{'id': 1527180, 'name': 'The Idea Shapers | Dr...",False,successful,2015-03-01 00:00:12,12500.00

### The following columns contain dictionary of dictionaries and subject to further parsing:
-category
-creator
-location
-profile

### JSON reader still looks like a good approach

In [19]:
parse_dict={"category":"df_category",
            "creator":"df_creator",                       
            "profile":"df_profile"
            }

In [20]:
for key, value in parse_dict.items():
      parse_dict[key] = pd.read_json(df_us_[key].to_json(orient="records"))

### Checking the parsed data to see if anything is relevant for the purpose of the project

In [21]:
parse_dict['category'].head(5)

### split 'slug' by "/" into 'category' and 'sub-category'
### get rid off everything else

,color,id,name,parent_id,position,slug,urls
0,14867664,48,Nonfiction,18,9,publishing/nonfiction,{'web': {'discover': 'http://www.kickstarter.c...
1,14867664,48,Nonfiction,18,9,publishing/nonfiction,{'web': {'discover': 'http://www.kickstarter.c...
2,14867664,48,Nonfiction,18,9,publishing/nonfiction,{'web': {'discover': 'http://www.kickstarter.c...
3,14867664,48,Nonfiction,18,9,publishing/nonfiction,{'web': {'discover': 'http://www.kickstarter.c...
4,14867664,48,Nonfiction,18,9,publishing/nonfiction,{'web': {'discover': 'http://www.kickstarter.c...

In [22]:
parse_dict['creator'].head(5)

,avatar,id,is_registered,name,slug,urls
0,{'small': 'https://ksr-ugc.imgix.net/assets/01...,1140825012,True,Ashley and Alex,NaN,{'api': {'user': 'https://api.kickstarter.com/...
1,{'small': 'https://ksr-ugc.imgix.net/assets/00...,1573482716,True,PM Press,ww3,{'api': {'user': 'https://api.kickstarter.com/...
2,{'small': 'https://ksr-ugc.imgix.net/assets/00...,1947700420,True,Doc Daniels,mojavephoneboothbook,{'api': {'user': 'https://api.kickstarter.com/...
3,{'small': 'https://ksr-ugc.imgix.net/assets/01...,733132432,True,Evelyn Johnson-Taylor,NaN,{'api': {'user': 'https://api.kickstarter.com/...
4,{'small': 'https://ksr-ugc.imgix.net/assets/00...,1642130654,True,Brandy Agerbeck,loosetooth,{'api': {'user': 'https://api.kickstarter.com/...

In [23]:
parse_dict['creator'].head(5)
### Keep 'name' (creator), 'is_registered'

,avatar,id,is_registered,name,slug,urls
0,{'small': 'https://ksr-ugc.imgix.net/assets/01...,1140825012,True,Ashley and Alex,NaN,{'api': {'user': 'https://api.kickstarter.com/...
1,{'small': 'https://ksr-ugc.imgix.net/assets/00...,1573482716,True,PM Press,ww3,{'api': {'user': 'https://api.kickstarter.com/...
2,{'small': 'https://ksr-ugc.imgix.net/assets/00...,1947700420,True,Doc Daniels,mojavephoneboothbook,{'api': {'user': 'https://api.kickstarter.com/...
3,{'small': 'https://ksr-ugc.imgix.net/assets/01...,733132432,True,Evelyn Johnson-Taylor,NaN,{'api': {'user': 'https://api.kickstarter.com/...
4,{'small': 'https://ksr-ugc.imgix.net/assets/00...,1642130654,True,Brandy Agerbeck,loosetooth,{'api': {'user': 'https://api.kickstarter.com/...

In [24]:
parse_dict['profile'].head(5)
### pretty useless (blurb is captured in 'df_parsed')

,background_color,background_image_attributes,background_image_opacity,blurb,feature_image_attributes,id,link_background_color,link_text,link_text_color,link_url,name,project_id,should_show_feature_image_section,show_feature_image,state,state_changed_at,text_color
0,,NaN,0.80,"“Eat Local In Barcelona"" breaks down the compl...",{'image_urls': {'default': 'https://ksr-ugc.im...,2219284,,,,,Eat Local in Barcelona - A Guide to Catalan Cu...,2219284,True,False,active,2016-03-28 22:53:50,
1,None,NaN,0.80,None,{'image_urls': {'default': 'https://ksr-ugc.im...,2044569,None,None,None,None,None,2044569,True,False,inactive,2015-07-31 21:22:59,None
2,None,NaN,0.80,None,{'image_urls': {'default': 'https://ksr-ugc.im...,1290905,None,None,None,None,None,1290905,True,False,inactive,2015-03-09 15:44:31,None
3,f9f7fa,NaN,0.69,The Heart of A Caregiver book will inspire tho...,{'image_urls': {'default': 'https://ksr-ugc.im...,2756887,,,,http://www.evelynjtaylor.org/bookstore,The Heart of A Caregiver My journey of caring ...,2756887,True,False,active,2016-12-15 21:59:39,1a2105
4,,NaN,0.80,The Idea Shapers book gives you the power to p...,{'image_urls': {'default': 'https://ksr-ugc.im...,1527180,ed1d0e,Buy the book!,,http://a.co/gOFb6Ud,The Idea Shapers | Drawing as your best thinki...,1527180,True,False,active,2016-12-12 23:00:20,

In [27]:
### Location column is different -  unable to parse it like other three columns.
### Below works, however

df_location = pd.DataFrame.from_dict(df_us_.location.to_dict()).transpose()
df_location.head(5)

### grab 'country', 'name' (city),  and 'state' (state)

,country,displayable_name,id,is_root,name,short_name,slug,state,type,urls
0,ES,"Barcelona, Spain",753692,False,Barcelona,"Barcelona, Spain",barcelona-barcelona-catalonia,Catalonia,Town,{'api': {'nearby_projects': 'https://api.kicks...
1,US,"Oakland, CA",2463583,False,Oakland,"Oakland, CA",oakland-ca,CA,Town,{'api': {'nearby_projects': 'https://api.kicks...
2,US,"South Bisbee, AZ",2495997,False,South Bisbee,"South Bisbee, AZ",south-bisbee-az,AZ,Town,{'api': {'nearby_projects': 'https://api.kicks...
3,US,"Tampa, FL",2503863,False,Tampa,"Tampa, FL",tampa-fl,FL,Town,{'api': {'nearby_projects': 'https://api.kicks...
4,US,"Chicago, IL",2379574,False,Chicago,"Chicago, IL",chicago-il,IL,Town,{'api': {'nearby_projects': 'https://api.kicks...

In [28]:
### 'deadline' date is in timestamp format
### Convert to human-readable format, save as a new column, 'deadline_dt'

import datetime

def time_to_date(row):
    return datetime.datetime.fromtimestamp(row['deadline']).strftime('%Y-%m-%d %H:%M:%S')


df_us_['deadline_dt'] = df_us_.apply(time_to_date, axis =1)

### Now compile all the data back together
### Renaming/dropping columns as needed

In [30]:
### Dataframe containing primary (most important) features: df_us_
### Drop columns that will be replaced with 

df_us_.drop(['category','creator','location','profile','deadline'], axis=1, inplace = True)

In [55]:
### Dataframe with location of the project (doesn't always coincide with 'country' of project creator)
### Grab 'country', 'name' (city),  and 'state' (state)
df_loc = df_location[['country','name','state']]
df_loc = df_loc.rename(columns={'country':'loc_country','name':'loc_name','state':'loc_state'})

In [32]:
### Dataframe with details on creator of the project 
### Grab 'name' (creator/company name(s)),  and 'is_registered'
df_crea = parse_dict['creator'].drop(['avatar','id','slug','urls'],axis=1).rename(columns={'name':'creator_name',
                                                                                 'is_registered':'creator_registered'})

In [33]:
### Dataframe with details on category of the project 
### Split 'slug' into 'category' and 'subcategory'
parse_dict['category']['category_'] = parse_dict['category']['slug'].str.split('/')
parse_dict['category']['category'] =parse_dict['category']['category_'].str[0]
parse_dict['category']['subcategory'] = parse_dict['category']['category_'].str[1]

### Get rid off other columns
df_cat = parse_dict['category'][['category','subcategory']]

In [34]:
### Check that the shapes of all dataframes are as expected
print(df_cat.shape)
print(df_crea.shape)
print(df_loc.shape)
print(df_us_.shape)

(140750, 2)
(140750, 2)
(140750, 3)
(140750, 15)

In [35]:
### Since order of rows has been intact on all 4 dataframes,
### joining them row by row into one final 

df_final = pd.concat([df_us_, df_cat, df_crea, df_loc], axis=1, join='inner')

In [43]:
df_final.head(3)

,backers_count,blurb,country,created_at,currency,goal,id,launched_at,name,pledged,...,state_changed_at,usd_pledged,deadline_dt,category,subcategory,creator_registered,creator_name,loc_country,loc_name,loc_state
0,29,"“Eat Local In Barcelona"" breaks down the compl...",US,2015-11-09 17:19:18,USD,2500.0,320979084,2016-02-25 17:54:23,Eat Local in Barcelona - A Guide to Catalan Cu...,2700.00,...,2016-03-26 16:54:23,2700.00,2016-03-26 11:54:23,publishing,nonfiction,True,Ashley and Alex,ES,Barcelona,Catalonia
1,505,Help us spark intelligent discussions about ra...,US,2015-07-31 21:22:59,USD,10000.0,439696234,2015-09-15 21:18:32,Understanding Jim Crow: Racist Memorabilia & S...,17321.00,...,2015-10-16 22:00:13,17321.00,2015-10-16 17:00:00,publishing,nonfiction,True,PM Press,US,Oakland,CA
2,172,How I accidentally made a desert phone booth w...,US,2014-08-14 23:59:45,USD,7900.0,820236173,2014-08-21 19:01:01,Adventures with the Mojave Phone Booth,8773.17,...,2014-09-20 19:01:03,8773.17,2014-09-20 14:01:01,publishing,nonfiction,True,Doc Daniels,US,South Bisbee,AZ

In [37]:
### Check country of project location (as opposed to creator location) distribution
df_final.loc_country.value_counts()

US    134780
CA       400
GB       341
JP       279
DE       235
CN       213
FR       206
IT       176
MX       166
ES       122
IN       114
PR       110
KR       106
IL        99
UA        95
AU        93
BR        84
TW        78
CO        73
AR        72
SE        69
TH        66
RU        62
CZ        59
HK        58
ZA        57
SI        57
PL        55
PE        55
PH        52
       ...
BH         1
PY         1
MR         1
CF         1
SZ         1
MO         1
LS         1
TC         1
BJ         1
CV         1
LY         1
SA         1
KW         1
SX         1
TJ         1
GY         1
DJ         1
GA         1
FJ         1
UZ         1
MC         1
XK         1
GQ         1
LC         1
PG         1
ME         1
BM         1
GP         1
MH         1
YE         1
Name: loc_country, dtype: int64

In [42]:
### For cleaner results, drop non-US-located projects

df_final_ = df_final.query('loc_country == country').reset_index().drop('index',axis=1)
print(df_final_.head(5))
print(df_final_.shape)

   backers_count                                              blurb country  \
0            505  Help us spark intelligent discussions about ra...      US
1            172  How I accidentally made a desert phone booth w...      US
2             31  The Heart of A Caregiver book will inspire tho...      US
3            274  The Idea Shapers book gives you the power to p...      US
4             23  I began writing this book in prison, it is my ...      US

           created_at currency     goal          id         launched_at  \
0 2015-07-31 21:22:59      USD  10000.0   439696234 2015-09-15 21:18:32
1 2014-08-14 23:59:45      USD   7900.0   820236173 2014-08-21 19:01:01
2 2016-11-12 20:56:09      USD   2500.0  1522087420 2016-11-15 18:11:50
3 2014-11-20 04:45:57      USD   5000.0  1079350420 2015-01-28 21:58:24
4 2017-03-05 01:16:53      USD   3000.0    15408858 2017-03-05 04:19:59

                                                name   pledged    ...     \
0  Understanding Jim Crow: Racist Memorabilia & S...  17321.00    ...
1             Adventures with the Mojave Phone Booth   8773.17    ...
2  The Heart of A Caregiver My journey of caring ...   2520.00    ...
3  The Idea Shapers | Drawing as your best thinki...  12500.00    ...
4  "87 Sundays" a True Story of Addiction, Recove...   3000.00    ...

     state_changed_at usd_pledged          deadline_dt    category  \
0 2015-10-16 22:00:13    17321.00  2015-10-16 17:00:00  publishing
1 2014-09-20 19:01:03     8773.17  2014-09-20 14:01:01  publishing
2 2016-12-15 18:11:50     2520.00  2016-12-15 12:11:50  publishing
3 2015-03-01 00:00:12    12500.00  2015-02-28 18:00:00  publishing
4 2017-04-14 03:20:01     3000.00  2017-04-13 22:19:59  publishing

  subcategory creator_registered           creator_name loc_country  \
0  nonfiction               True               PM Press          US
1  nonfiction               True            Doc Daniels          US
2  nonfiction               True  Evelyn Johnson-Taylor          US
3  nonfiction               True        Brandy Agerbeck          US
4  nonfiction               True   John "Johnny" Baxter          US

       loc_name loc_state
0       Oakland        CA
1  South Bisbee        AZ
2         Tampa        FL
3       Chicago        IL
4        Dayton        OH

[5 rows x 22 columns]
(134780, 22)

In [46]:
### Checking distribution of project outcomes ('state')
df_final_.state.value_counts()

failed        62893
successful    60606
canceled       8469
live           2277
suspended       535
Name: state, dtype: int64

In [49]:
### Checking if all 15 categories are represented 
df_final_.category.nunique()

15

In [57]:
### Pickle it
pickle.dump(df_final_,open("kicks_modeling_data.pkl",'wb'))

### Next step - load kicks_modeling_data.pkl into Mongo DB collection 'kickstarter' in 'new_cool_db'